// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int number = Integer.parseInt(args[0]);
		double random = 0, Ratio = 0;
		double bigger = 0.0, smaller = 0.0;
		for(int count = 0; count < number; count++){
        random = Math.random();
		if(random > 0.5){
		bigger++;
		}
		if(random <= 0.5){
		smaller++;
		}
		}
		if(smaller != 0){
		Ratio = bigger / smaller;
		System.out.println("> 0.5: " + (int)bigger + " times");
		System.out.println("<= 0.5: " + (int)smaller + " times");
		System.out.println("Ratio:" + Ratio);
		}
		else{
		System.out.println("> 0.5: " + (int)bigger + " times");
		System.out.println("<= 0.5: " + (int)smaller + " times");
		}
	}
}
